"""Plant a parameter, hide it, and see whether the pipeline finds it again.

WHY THIS IS THE FIRST THING BUILT, before any corpus arrives. `lab/fit-auto.js` refuses to run
without an isolation pass because its first version "succeeded" by driving the knobs it was tuning
to their off values. `lab/fit-dynamics.js --check` plants a known voice, overwrites its targets with
what that voice measures, starts the search elsewhere and reports recovery. `lab/artspace.js` does
the same for the posture inversion. The rule those three encode is that a fitter is not believed
until it has recovered a planted answer, and it costs nothing to obey it here.

It also answers a question that has nothing to do with mngu0 and cannot wait for it: **is a
parameter identifiable from a trajectory at all?** If planting `artT` and searching for it does not
find it on synthetic data generated by the model itself — where the answer is exactly representable
and there is no registration, no sensor noise and no annotation error — then it will certainly not
be found in a corpus, and the reason will be the parameter rather than the data.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

import numpy as np

from .tracks import Run, rms_difference, run

# Short and phonetically varied. Long enough to contain real transitions, few enough that a scan
# costs seconds — one `--actual` pass is about a second an utterance.
PROBE = [
    "u1\tthe quick brown fox jumps over the lazy dog",
    "u2\tshe sells sea shells",
    "u3\tI love my daughter",
]


@dataclass
class Recovery:
    parameter: str
    planted: float
    found: float
    grid: list[float]
    error: list[float]

    @property
    def miss(self) -> float:
        return abs(self.found - self.planted)

    def __str__(self) -> str:
        worst = max(self.error)
        floor = min(self.error)
        return (f"{self.parameter}: planted {self.planted:g}, found {self.found:g} "
                f"(miss {self.miss:g}); objective spans {floor:.5f}..{worst:.5f}")


def recover(parameter: str, planted: float, grid: list[float],
            utterances: list[str] | None = None, base: Run | None = None) -> Recovery:
    """Generate trajectories at `planted`, then scan `grid` for the value that reproduces them.

    The scan is exhaustive rather than a descent. Six of these parameters interact and none of them
    is known to be convex in trajectory error, so a local method here would be reporting the shape
    of its own start point. A grid is affordable at this size and says something a descent does not:
    the whole error curve, from which identifiability can be read directly.
    """
    base = base or Run(utterances=utterances or PROBE)
    truth = run(replace(base, overrides={**base.overrides, parameter: planted}))

    err = []
    for x in grid:
        got = run(replace(base, overrides={**base.overrides, parameter: x}))
        err.append(rms_difference(truth, got))

    return Recovery(parameter=parameter, planted=planted,
                    found=float(grid[int(np.argmin(err))]), grid=list(grid), error=err)


def is_identifiable(r: Recovery, tol: float, flat: float = 1e-6) -> tuple[bool, str]:
    """Did the scan actually locate the answer, and did the objective have a shape to locate it by?

    Two ways this can pass while meaning nothing, both worth naming rather than discovering later:
    a flat objective, where every value fits equally well and the argmin is noise; and an objective
    minimised at the edge of the grid, where the true answer may be outside it.
    """
    span = max(r.error) - min(r.error)
    if span < flat:
        return False, f"objective is flat ({span:.2e}) — {r.parameter} is not identifiable here"
    if r.found in (r.grid[0], r.grid[-1]) and r.planted not in (r.grid[0], r.grid[-1]):
        return False, f"minimum sits at the edge of the grid — widen it past {r.found:g}"
    if r.miss > tol:
        return False, f"missed by {r.miss:g}, wanted {tol:g}"
    return True, str(r)
